AllCops:
  NewCops: enable
  Include:
    - app/**/*
    - spec/**/*
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - db/seeds.rb
    - Gemfile
    - Gemfile.lock
    - bin/*
    - vendors/**/*
    - Rakefile
    - config.ru
    - config/**/*
    - data/**/*
    - spec/examples.txt
  TargetRubyVersion: 2.7
