FORMAT: 1A
# Tunisia Open Data API

# Group Cities

## Cities Collection [/v1/cities]

### get cities [GET]

+ Request get cities. (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json

+ Response 200 ()

    + Body

            [binary data]
